"use client";

import { useState } from "react";
import { toast } from "sonner";

type Participant = { id: string; name: string; userId: string | null };
type Bill = { id: string; title: string; status: string; creatorId: string; participants: Participant[]; expenses: { id: string; title: string; amountAed: number; method: string; payer: string; splits: { name: string; amountAed: number }[] }[]; transfers: { id: string; from: string; fromUserId: string | null; to: string; amountAed: number; status: string }[] };

export function BillDetail({ slug, bill, currentUserId }: { slug: string; bill: Bill; currentUserId: string }) {
  const mine = bill.creatorId === currentUserId; const [title, setTitle] = useState(""); const [amount, setAmount] = useState(""); const [payer, setPayer] = useState(bill.participants[0]?.id ?? ""); const [method, setMethod] = useState<"EQUAL" | "EXACT_AMOUNT" | "PERCENTAGE" | "SHARES">("EQUAL"); const [selected, setSelected] = useState(bill.participants.map((item) => item.id)); const [values, setValues] = useState<Record<string, string>>({});
  async function addExpense(event: React.FormEvent) {
    event.preventDefault(); const amountAed = Number(amount); if (!selected.length || !amountAed) return toast.error("请填写金额并选择分摊对象。");
    const split = method === "EQUAL" ? { method, participantIds: selected } : method === "EXACT_AMOUNT" ? { method, amounts: selected.map((participantId) => ({ participantId, amountFils: Math.round(Number(values[participantId] ?? 0) * 100) })) } : method === "PERCENTAGE" ? { method, percentages: selected.map((participantId) => ({ participantId, basisPoints: Math.round(Number(values[participantId] ?? 0) * 100) })) } : { method, shares: selected.map((participantId) => ({ participantId, shares: Number(values[participantId] ?? 0) })) };
    const response = await fetch(`/api/circles/${slug}/bills/${bill.id}/expenses`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, amountAed, payerParticipantId: payer, split }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error ?? "新增支出失败。"); toast.success("支出已加入账单。"); window.location.reload();
  }
  async function settlement(action: "SETTLE" | "REOPEN" | "MARK_PAID", transferId?: string) { const response = await fetch(`/api/circles/${slug}/bills/${bill.id}/settlement`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, transferId }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error ?? "操作失败。"); toast.success(action === "MARK_PAID" ? "已标记付款。" : action === "SETTLE" ? "已生成结算建议。" : "账单已重新开启。"); window.location.reload(); }
  return <div className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-4xl font-bold tracking-tight">{bill.title}</h1><p className="mt-2 text-sm text-[var(--muted)]">状态：{bill.status} · 参与者：{bill.participants.map((item) => item.name).join("、")}</p></div>{mine && <button className="rounded-xl bg-[var(--brand)] px-4 py-3 font-semibold text-white" onClick={() => settlement(bill.status === "SETTLED" ? "REOPEN" : "SETTLE")}>{bill.status === "SETTLED" ? "重新开启账单" : "生成结算建议"}</button>}</div>
    {mine && bill.status !== "SETTLED" && <form className="mt-6 space-y-4 rounded-3xl border border-[var(--line)] bg-white p-5" onSubmit={addExpense}><h2 className="text-lg font-bold">录入支出</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">名称<input className="mt-2 w-full rounded-xl border border-[var(--line)] px-3 py-3" required value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="text-sm font-medium">金额（AED）<input className="mt-2 w-full rounded-xl border border-[var(--line)] px-3 py-3" required min="0.01" step="0.01" type="number" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className="text-sm font-medium">付款人<select className="mt-2 w-full rounded-xl border border-[var(--line)] px-3 py-3" value={payer} onChange={(event) => setPayer(event.target.value)}>{bill.participants.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">分摊方式<select className="mt-2 w-full rounded-xl border border-[var(--line)] px-3 py-3" value={method} onChange={(event) => setMethod(event.target.value as typeof method)}><option value="EQUAL">均分</option><option value="EXACT_AMOUNT">不等额金额</option><option value="PERCENTAGE">按比例</option><option value="SHARES">按份数</option></select></label></div><div className="grid gap-2 sm:grid-cols-2">{bill.participants.map((item) => <label className="flex items-center gap-2 rounded-xl border border-[var(--line)] p-3 text-sm" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected((ids) => ids.includes(item.id) ? ids.filter((id) => id !== item.id) : [...ids, item.id])} />{item.name}{method !== "EQUAL" && selected.includes(item.id) && <input className="ml-auto w-24 rounded-lg border border-[var(--line)] px-2 py-1" placeholder={method === "PERCENTAGE" ? "%" : method === "SHARES" ? "份" : "AED"} type="number" step={method === "EXACT_AMOUNT" ? "0.01" : "1"} value={values[item.id] ?? ""} onChange={(event) => setValues({ ...values, [item.id]: event.target.value })} />}</label>)}</div><p className="text-xs text-[var(--muted)]">比例合计必须为 100%；不等额金额合计必须等于支出金额。系统会以 fils（AED 的 1/100）精确计算。</p><button className="rounded-xl bg-[var(--brand)] px-4 py-3 font-semibold text-white">新增支出</button></form>}
    <section className="mt-6 space-y-3"><h2 className="text-xl font-bold">支出明细</h2>{bill.expenses.map((item) => <article key={item.id} className="rounded-2xl border border-[var(--line)] bg-white p-4"><div className="flex justify-between gap-3"><strong>{item.title}</strong><strong>AED {item.amountAed.toFixed(2)}</strong></div><p className="mt-2 text-sm text-[var(--muted)]">付款：{item.payer} · {item.method} · {item.splits.map((split) => `${split.name} AED ${split.amountAed.toFixed(2)}`).join("；")}</p></article>)}{bill.expenses.length === 0 && <p className="rounded-2xl border border-dashed border-[var(--line)] p-5 text-[var(--muted)]">尚未录入支出。</p>}</section>
    {bill.status === "SETTLED" && <section className="mt-6 space-y-3"><h2 className="text-xl font-bold">转账建议</h2>{bill.transfers.map((item) => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--line)] bg-white p-4"><p>{item.from} → {item.to} · <strong>AED {item.amountAed.toFixed(2)}</strong></p>{item.status === "PENDING" && item.fromUserId === currentUserId ? <button className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm font-semibold" onClick={() => settlement("MARK_PAID", item.id)}>标记已付款</button> : <span className="text-xs text-[var(--muted)]">{item.status}</span>}</article>)}</section>}
  </div>;
}
