"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

type Member = { userId: string; name: string; role: string };
export function CircleManagement({ slug, role, members, applications }: { slug: string; role: string; members: Member[]; applications: { id: string; name: string; email: string; invitationType: string | null }[] }) {
  const router = useRouter();
  const manager = role === "OWNER" || role === "ADMIN"; const owner = role === "OWNER"; const [invite, setInvite] = useState(""); const [expiresAt, setExpiresAt] = useState(""); const [maxUses, setMaxUses] = useState("");
  async function createInvite(event: React.FormEvent) { event.preventDefault(); const response = await fetch(`/api/circles/${slug}/invitations`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type: "LINK", expiresAt: expiresAt ? new Date(expiresAt).toISOString() : undefined, maxUses: maxUses ? Number(maxUses) : undefined }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error ?? "创建邀请失败。"); setInvite(body.url); toast.success("邀请已创建，可复制链接分享。"); }
  async function review(applicationId: string, approve: boolean) { const response = await fetch(`/api/circles/${slug}/manage/applications`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ applicationId, approve }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error ?? "审批失败。"); toast.success(approve ? "已通过申请。" : "已拒绝申请。"); window.location.reload(); }
  async function memberAction(userId: string, action: "SET_ROLE" | "TRANSFER_OWNERSHIP", nextRole?: "ADMIN" | "MEMBER") { if (action === "TRANSFER_OWNERSHIP" && !window.confirm("确认转让圈主身份？你将成为管理员。")) return; const response = await fetch(`/api/circles/${slug}/manage/members/${userId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, role: nextRole }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error ?? "成员调整失败。"); toast.success("成员权限已更新。"); window.location.reload(); }
  async function dissolve(mode: "DELETE_NOW" | "RETAIN_7_DAYS") { if (!window.confirm(mode === "DELETE_NOW" ? "立即删除将移除全部成员和圈子数据，确认继续？" : "确认解散圈子并保留 7 天恢复期？")) return; const response = await fetch(`/api/circles/${slug}/dissolution`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error ?? "解散失败。"); router.push("/app"); }
  return <div className="mt-8 space-y-8"><form className="rounded-3xl border border-[var(--line)] bg-white p-5" onSubmit={createInvite}><h2 className="text-xl font-bold">创建邀请</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">失效时间（可选）<input className="mt-2 w-full rounded-xl border border-[var(--line)] px-3 py-3" type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></label><label className="text-sm font-medium">最大使用次数（可选）<input className="mt-2 w-full rounded-xl border border-[var(--line)] px-3 py-3" min="1" type="number" value={maxUses} onChange={(event) => setMaxUses(event.target.value)} /></label></div><button className="mt-4 rounded-xl bg-[var(--brand)] px-4 py-3 font-semibold text-white">生成邀请链接</button>{invite && <div className="mt-4 rounded-xl bg-[var(--brand-soft)] p-3 text-sm break-all"><strong>链接：</strong>{invite}</div>}</form>
    {manager && <section><h2 className="text-xl font-bold">待审批申请</h2><div className="mt-3 space-y-3">{applications.map((application) => <article className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--line)] bg-white p-4" key={application.id}><span>{application.name} <small className="text-[var(--muted)]">{application.invitationType ? `（邀请：${application.invitationType}）` : "（广场申请）"}</small></span><span className="flex gap-2"><button className="rounded-lg bg-[var(--brand)] px-3 py-2 text-sm font-semibold text-white" onClick={() => review(application.id, true)}>通过</button><button className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm font-semibold" onClick={() => review(application.id, false)}>拒绝</button></span></article>)}{applications.length === 0 && <p className="text-sm text-[var(--muted)]">没有待审批申请。</p>}</div></section>}
    {manager && <section><h2 className="text-xl font-bold">成员与权限</h2><div className="mt-3 space-y-3">{members.map((member) => <article className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--line)] bg-white p-4" key={member.userId}><span>{member.name} <small className="ml-2 font-semibold text-[var(--brand)]">{member.role}</small></span>{owner && member.role !== "OWNER" && <span className="flex gap-2"><button className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm" onClick={() => memberAction(member.userId, "SET_ROLE", member.role === "ADMIN" ? "MEMBER" : "ADMIN")}>{member.role === "ADMIN" ? "撤销管理员" : "任命管理员"}</button><button className="rounded-lg border border-[var(--line)] px-3 py-2 text-sm" onClick={() => memberAction(member.userId, "TRANSFER_OWNERSHIP")}>转让圈主</button></span>}</article>)}</div></section>}
    {owner && <section className="rounded-3xl border border-red-200 bg-red-50 p-5"><h2 className="text-xl font-bold text-red-800">解散圈子</h2><p className="mt-2 text-sm text-red-700">立即删除不可恢复；保留 7 天可在恢复期内重新开启。</p><div className="mt-4 flex flex-wrap gap-3"><button className="rounded-xl border border-red-300 px-4 py-3 text-sm font-semibold text-red-800" onClick={() => dissolve("RETAIN_7_DAYS")}>解散并保留 7 天</button><button className="rounded-xl bg-red-700 px-4 py-3 text-sm font-semibold text-white" onClick={() => dissolve("DELETE_NOW")}>立即删除</button></div></section>}
  </div>;
}
